### ISSUE TITLE
View text on stamps homepage not wrapped with link

### ISSUE THREAD

**Issue by PBillingsby** [twilson63/stamps#1]
When I try to click the "View" text on individual assets to view them on the stamps landing, the "View" text isn't wrapped with a link and does not redirect to that asset.

Current structure has two nested divs, the second one being the parent of the link itself, which makes it so the "View" div isn't clickable 
```
<div class="flex flex-col"><div class="font-bold">View</div> <div><a target="_blank" href="https://arweave.net/Jb8sFNUbDtIVwE6O9INGSWkH2xgKQKdrDg_kQjvQ4n4"><img src="assets/view.svg" class="h-[24px] w-[24px]" alt="view asset"></a></div></div>
```

**Comment by twilson63** [comment]
This should be fixed!
